src/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root 'about#about'

    resources :visits do
      collection do
        get 'for_date' # Get visits for a specific date
        get 'max_stay_info' # Get max stay info for entry date
      end
    end
    resources :visas, except: [:index, :show]
    resources :days, only: [:index]
    resources :people do
      member do
        post :set_current
        post :make_primary
      end
    end
    
    get 'my_details' => 'users#edit'
    patch 'my_details' => 'users#update'
    delete 'my_details' => 'users#destroy', as: 'delete_account'
    get 'user' => 'users#show'
    get 'about' => 'about#about'
    get 'blog' => 'blogs#index', as: :blog_index
    get 'blog/:slug' => 'blogs#show', as: :blog
    get 'about/:nationality' => 'about#about'
    get 'disclaimer' => 'about#disclaimer'
    get 'privacy' => 'about#privacy'
    get 'datadeletion' => 'about#datadeletion'
    
    get 'fix_people_migration' => 'tasks#fix_people_migration'
    get 'unlock_migrations' => 'tasks#unlock_migrations'
    get 'unlock_and_migrate' => 'tasks#unlock_and_migrate'
    get 'migrate' => 'tasks#migrate'
    get 'create' => 'tasks#create'
    get 'seed' => 'tasks#seed'
    get 'update_countries' => 'tasks#update_countries'
    get 'guest_cleanup' => 'tasks#guest_cleanup'

    devise_for :users, skip: :omniauth_callbacks, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions'
    }

  end
  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
end

src/app/views/layouts/_agoda.haml
.row
  .col-sm-12
    %div{:style => "max-width:300px"}
      %ins.adsbygoogle{"data-ad-client" => "ca-pub-8290979932488448", "data-ad-format" => "auto", "data-ad-slot" => "4817228212", :style => "display:block"}
/ .row
/   .col-sm-12
/     %h3
/       =link_to "Agoda", "http://www.agoda.com?cid=1750660_60248", target: "_blank", rel:"nofollow"
/       is the most convienent way to book accomodation, and always the best prices!
      
/ .row
/   .col-sm-12.amazon
/     :javascript
/       agoda_ad_client = "1750660_60248";
/       agoda_ad_width = 300;
/       agoda_ad_height = 600;
/     %script{:src => "//banner.agoda.com/js/show_ads.js", :type => "text/javascript"}
:javascript
  (adsbygoogle = window.adsbygoogle || []).push({});

src/app/views/layouts/_amazon.haml
.row
  .col-sm-12
    %ins.adsbygoogle{"data-ad-client" => "ca-pub-8290979932488448", "data-ad-format" => "auto", "data-ad-slot" => "4817228212", :style => "display:block"}
.row
  .col-sm-12
    %h3
      Recommended Travel Books
.row
  .col-sm-12.amazon
    - if amazon
      - amazon.items.each do |item|
        .amazon-item
          %a{ href: item.page_url }
            .a-image
              %img{ src: item.image_url, alt: item.title, border: 0 }
            .a-area
              = item.title
            .a-area
              = item.price
/ :javascript
/   (adsbygoogle = window.adsbygoogle || []).push({});

src/app/views/layouts/_footer.haml
%footer.footer.bg-light
  .container-fluid
    .row.align-items-center.py-2.justify-content-between
      - if rtl_locale?
        .col-auto.text-center.text-lg-right
          .language-selector-wrapper
            %i.fa.fa-globe.mr-2.text-primary.d-none.d-md-inline
            = language_selector
        .col.text-center.mb-2.mb-lg-0.d-none.d-md-block
          %nav.footer-links{"aria-label": "Legal"}
            = link_to disclaimer_path(locale: I18n.locale), class: "footer-link text-nowrap" do
              %i.fa.fa-file-text.mr-1
              = t('common.disclaimer')
            %span.mx-2.text-muted ·
            = link_to privacy_path(locale: I18n.locale), class: "footer-link text-nowrap" do
              %i.fa.fa-shield-alt.mr-1
              = t('common.privacy_policy')
            %span.mx-2.text-muted ·
            = link_to datadeletion_path(locale: I18n.locale), class: "footer-link text-nowrap" do
              %i.fa.fa-trash.mr-1
              = t('common.data_deletion')
        .col-auto.text-center.text-lg-left
          %span.text-muted.text-nowrap.footer-copyright
            %i.fa.fa-copyright.mr-1{"aria-hidden" => "true"}
            = "#{Time.current.year} #{t('common.schengen_calculator')}"
      - else
        .col-auto.text-center.text-lg-left
          %span.text-muted.text-nowrap.footer-copyright
            %i.fa.fa-copyright.mr-1{"aria-hidden" => "true"}
            = "#{Time.current.year} #{t('common.schengen_calculator')}"
        .col.text-center.mb-2.mb-lg-0.d-none.d-md-block
          %nav.footer-links{"aria-label": "Legal"}
            = link_to disclaimer_path(locale: I18n.locale), class: "footer-link text-nowrap" do
              %i.fa.fa-file-text.mr-1
              = t('common.disclaimer')
            %span.mx-2.text-muted ·
            = link_to privacy_path(locale: I18n.locale), class: "footer-link text-nowrap" do
              %i.fa.fa-shield-alt.mr-1
              = t('common.privacy_policy')
            %span.mx-2.text-muted ·
            = link_to datadeletion_path(locale: I18n.locale), class: "footer-link text-nowrap" do
              %i.fa.fa-trash.mr-1
              = t('common.data_deletion')
        .col-auto.text-center.text-lg-right
          .language-selector-wrapper
            %i.fa.fa-globe.mr-2.text-primary.d-none.d-md-inline
            = language_selector
%script{:type => "application/ld+json"}
  {
  "@context": "http://schema.org",
  "@type": "Organization",
  "url": "https://schengen-calculator.com",
  "logo": "https://schengen-calculator.com/med.png"
  }

/ Google tag (gtag.js)
%script{:async => "", :src => "https://www.googletagmanager.com/gtag/js?id=G-E9CCZDHLJF"}
:javascript
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-E9CCZDHLJF');

src/app/views/layouts/_header.haml
- rtl_layout = rtl_locale?
%nav.navbar.navbar-expand-md.navbar-light.bg-light.sticky-top{role: "navigation", "aria-label": "Main navigation", dir: (rtl_layout ? 'ltr' : nil)}
  %a.navbar-brand.px-3.px-md-0{:href => visits_path(I18n.locale)}
    = image_tag("logo.svg", alt: t('common.schengen_calculator'), width: 48, height: 48)
    %span.navbar-text.site-title{dir: "auto"}
      = t('common.schengen')
      %span.d-none.d-md-inline
        = t('common.visa')
      = t('common.calculator')
  %button.navbar-toggler{type: "button", "data-toggle" => "collapse", "data-target" => "#navbarContent", "aria-controls" => "navbarContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation"}
    %span.navbar-toggler-icon
  .collapse.navbar-collapse{id: "navbarContent"}
    %ul.navbar-nav.nav-tabs.mx-auto
      %li.nav-item{class: (active_if(controller: 'visits')) }
        %a.nav-link{href: visits_path(I18n.locale) }
          %i.fa.fa-plane.mr-2{"aria-hidden": "true"}
          = t('common.trips')
      %li.nav-item{class: (active_if(controller: 'days'))}
        %a.nav-link{href: days_path(locale: I18n.locale)}
          %i.fa.fa-calendar.mr-2{"aria-hidden": "true"}
          = t('common.calendar')
      %li.nav-item{class: (active_if(controller: 'about'))}
        %a.nav-link{href: about_path(locale: I18n.locale)}
          %i.fa.fa-info-circle.mr-2{"aria-hidden": "true"}
          = t('common.about')
      %li.nav-item{class: (active_if(controller: 'blogs'))}
        %a.nav-link{href: blog_index_path(locale: I18n.locale)}
          %i.fa.fa-book.mr-2{"aria-hidden": "true"}
          = t('common.blog')
    %ul.navbar-nav.ml-auto.text-right
      %li.nav-item.dropdown.person-switcher
        %a#personDropdown.nav-link.dropdown-toggle.d-md-flex.flex-column.align-items-md-end{href: "#", "data-toggle": "dropdown", "aria-haspopup": "true", "aria-expanded": "false"}
          %span.person-name{dir: "auto"}= current_person.full_name
          %small.person-nationality{dir: "auto"}= current_person.nationality&.localized_name || t('common.person_not_set')
        .dropdown-menu.dropdown-menu-md-right{"aria-labelledby": "personDropdown"}
          - current_user_or_guest_user.people.ordered.each do |person|
            = button_to set_current_person_path(person), class: ['dropdown-item', 'text-left', ('active' if person == current_person)], form: { class: 'dropdown-item-form w-100', data: { turbo: false } } do
              %span.d-flex.align-items-start
                - if person == current_person
                  %i.fa.fa-check.mr-2{"aria-hidden": "true"}
                - else
                  %span.mr-4
                .d-inline-block.text-left
                  %div= person.full_name
                  %small.text-muted.d-block= person.nationality&.localized_name || t('common.person_not_set')
          .d-none.d-md-block
            = link_to new_person_path(locale: I18n.locale), class: "dropdown-item" do
              %i.fa.fa-plus.mr-2{"aria-hidden": "true"}
              = t('common.add_person')
            .dropdown-divider
            = link_to people_path(locale: I18n.locale), class: "dropdown-item" do
              %i.fa.fa-users.mr-2{"aria-hidden": "true"}
              = t('common.manage_people')
            = link_to edit_person_path(current_person, locale: I18n.locale), class: "dropdown-item" do
              %i.fa.fa-edit.mr-2{"aria-hidden": "true"}
              = t('common.edit_current_person')
            .dropdown-divider
            - if user_signed_in?
              = link_to my_details_path(locale: I18n.locale), class: "dropdown-item" do
                %i.fa.fa-user-cog.mr-2{"aria-hidden": "true"}
                = t('common.manage_account')
            - else
              = link_to new_user_registration_path(locale: I18n.locale), class: "dropdown-item text-primary font-weight-bold" do
                %i.fa.fa-user-plus.mr-2{"aria-hidden": "true"}
                = t('common.register_to_save')
      %li.nav-item.d-md-none
        = link_to new_person_path(locale: I18n.locale), class: "nav-link" do
          %i.fa.fa-plus.mr-2{"aria-hidden": "true"}
          = t('common.add_person')
      %li.nav-item.d-md-none
        = link_to people_path(locale: I18n.locale), class: "nav-link" do
          %i.fa.fa-users.mr-2{"aria-hidden": "true"}
          = t('common.manage_people')
      %li.nav-item.d-md-none
        = link_to edit_person_path(current_person, locale: I18n.locale), class: "nav-link" do
          %i.fa.fa-edit.mr-2{"aria-hidden": "true"}
          = t('common.edit_current_person')
      - if user_signed_in?
        %li.nav-item.d-md-none
          = link_to my_details_path(locale: I18n.locale), class: "nav-link" do
            %i.fa.fa-user-cog.mr-2{"aria-hidden": "true"}
            = t('common.manage_account')
      - else
        %li.nav-item.d-md-none
          = link_to new_user_registration_path(locale: I18n.locale), class: "nav-link text-primary font-weight-bold" do
            %i.fa.fa-user-plus.mr-2{"aria-hidden": "true"}
            = t('common.register_to_save')
      - if user_signed_in?
        %li.nav-item.d-flex.align-items-center.justify-content-end
          %a.btn.btn-outline-dark.btn-sm{href: "#", onclick: "document.getElementById('logout-form').submit(); return false;", "aria-label": t('common.log_out')}
            %i.fa.fa-sign-out-alt.mr-2{"aria-hidden": "true"}
            = t('common.log_out')
          %form#logout-form{action: destroy_user_session_path, method: :post, style: "display: none;"}
            = hidden_field_tag :_method, :delete
            = hidden_field_tag :authenticity_token, form_authenticity_token
      - else
        %li.nav-item.d-flex.align-items-center.justify-content-end
          = link_to new_user_session_path(locale: I18n.locale), class: 'btn btn-primary ml-2' do
            %i.fa.fa-sign-in-alt.mr-2
            = t('common.login')
      / Buy Me a Coffee - visible only on mobile
      %li.nav-item.d-md-none.mt-3.text-center
        = link_to "https://www.buymeacoffee.com/smclean17d", target: "_blank", rel: "noopener noreferrer", "aria-label": "Buy me a coffee" do
          = image_tag "https://cdn.buymeacoffee.com/buttons/v2/default-yellow.png", alt: "Buy Me A Coffee", style: "height: 40px; width: auto;"
      / Legal links - visible only on mobile
      %li.nav-item.d-md-none.mt-3.pt-3.border-top
        %small.text-muted.d-block.mb-2.px-3= t('common.legal')
        .legal-links-mobile
          = link_to disclaimer_path(locale: I18n.locale), class: "d-block px-3 py-2 text-muted small" do
            %i.fa.fa-file-text.mr-2
            = t('common.disclaimer')
          = link_to privacy_path(locale: I18n.locale), class: "d-block px-3 py-2 text-muted small" do
            %i.fa.fa-shield-alt.mr-2
            = t('common.privacy_policy')
          = link_to datadeletion_path(locale: I18n.locale), class: "d-block px-3 py-2 text-muted small" do
            %i.fa.fa-trash.mr-2
            = t('common.data_deletion')

src/app/views/layouts/_notice.haml
- if flash[:notice]
  .alert.alert-success.alert-dismissible.fade.show{role: "alert", id: "success"}
    = flash[:notice]
    %button.btn.btn-sm.py-0.close{"type" => "button", "data-dismiss" => "alert", "aria-label" => "Close"}
      %span{"aria-hidden" => "true"} &times;

- if flash[:alert]
  .alert.alert-warning.alert-dismissible.fade.show{role: "alert", id: "notice"}
    = flash[:alert]
    %button.btn.btn-sm.py-0.close{"type" => "button", "data-dismiss" => "alert", "aria-label" => "Close"}
      %span{"aria-hidden" => "true"} &times;

src/app/views/layouts/application.html.erb
<!DOCTYPE html>
<% direction = I18n.locale.to_sym == :ar ? 'rtl' : 'ltr' %>
<html lang="<%= I18n.locale %>" dir="<%= direction %>">
<head>
  <!-- Preconnect to external domains for faster resource loading -->
  <!-- Google Fonts (critical for styling) -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  
  <!-- Third-party services (ads, analytics, social) -->
  <link rel="preconnect" href="https://pagead2.googlesyndication.com">
  <link rel="preconnect" href="https://www.google-analytics.com">
  <link rel="preconnect" href="https://connect.facebook.net">
  <link rel="dns-prefetch" href="https://www.googletagmanager.com">
  
  <!-- Preload critical assets -->
  <link rel="preload" href="<%= asset_path('application.css') %>" as="style">
  
  <!-- Critical CSS for LCP optimization - inlined to eliminate render delay -->
  <style><%= critical_css.html_safe %></style>

  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="msvalidate.01" content="78EB2E60264CB939006FF5C07C8F2404">
  <meta http-equiv="content-language" content="<%= I18n.locale %>">
  <meta name="referrer" content="no-referrer-when-downgrade">
  <meta name="referrer-policy" content="no-referrer-when-downgrade">
  <% if request.host.include?('test.') %>
  <!-- Staging environment - prevent search engine indexing -->
  <meta name="robots" content="noindex, nofollow">
  <% end %>
  <meta name="description" content="<%= @meta_description || (content_for?(:description) ? yield(:description) : t('default_description')) %>" />
  <meta name="keywords" content="<%= t('keywords') %>">
  <meta property="og:type" content="<%= @og_type || 'website' %>" />
  <meta property="og:url" content="<%= @og_url || "https://#{request.host_with_port}#{request.path}" %>" />
  <meta property="og:title" content="<%= @meta_title || (content_for?(:title) ? t('title_with_content', content: yield(:title)) : t('default_title')) %>" />
  <meta property="og:description" content="<%= @meta_description || (content_for?(:description) ? yield(:description) : t('default_description')) %>" />
  <meta property="og:image" content="<%= @og_image || 'https://schengen-calculator.com/med.png' %>" />
  <meta property="og:image:width" content="1200" />
  <meta property="og:image:height" content="630" />
  <% if @og_site_name %><meta property="og:site_name" content="<%= @og_site_name %>" /><% end %>
  <% if @article_published_time %><meta property="article:published_time" content="<%= @article_published_time %>" /><% end %>
  <% if @article_modified_time %><meta property="article:modified_time" content="<%= @article_modified_time %>" /><% end %>
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:title" content="<%= @meta_title || (content_for?(:title) ? t('title_with_content', content: yield(:title)) : t('default_title')) %>" />
  <meta name="twitter:description" content="<%= @meta_description || (content_for?(:description) ? yield(:description) : t('default_description')) %>" />
  <meta name="twitter:image" content="<%= @og_image || 'https://schengen-calculator.com/med.png' %>" />


  <% canonical_tag = 'https://' + request.host_with_port + request.path %>
  <% locales_pattern = I18n.available_locales.map(&:to_s).join('|') %>
  <% alternate_path = '' %>
  <% alternate_path2 = '' %>
  <% alternate_path3 = '' %>
  <% alternate_path_other_lang = '' %>
  <% if request.path == '/en' || request.path == '/' || request.path == '/en/about' || request.path == '/about'  %>
    <% canonical_tag = 'https://' + request.host_with_port + '/' %>
    <% alternate_path = 'https://' + request.host_with_port + '/about' %>
    <% alternate_path2 = 'https://' + request.host_with_port + '/en/about' %>
    <% alternate_path3 = 'https://' + request.host_with_port + '/en' %>
  <% elsif request.path.starts_with?('/en/') %>
    <% canonical_tag = 'https://' + request.host_with_port + request.path.sub('/en/', '/') %>
    <% alternate_path2 = 'https://' + request.host_with_port + request.path %>
  <% elsif request.path =~ /^\/(#{locales_pattern})(\/.*)?$/ %>
    <% canonical_tag = 'https://' + request.host_with_port + request.path %>
    <% alternate_path_other_lang = canonical_tag %>
      <% if canonical_tag.end_with?('/about') %>
        <% alternate_path2 = canonical_tag %>
        <% canonical_tag = canonical_tag.sub(/\/about\z/, '') %>
        <% alternate_path_other_lang = canonical_tag %>
      <% end %>
      <% if canonical_tag =~ /\/(#{locales_pattern})\z/ %>
        <% alternate_path2 = canonical_tag + '/about' %>
      <% end %>
  <% else %>
    <% alternate_path2 = 'https://' + request.host_with_port + '/en' + request.path %>
  <% end %>

  <link rel="canonical" href="<%= canonical_tag %>" hreflang="<%= locale.to_s %>" />
  <% if alternate_path.present? %>
    <link rel="alternate" href="<%= alternate_path %>" hreflang="<%= locale.to_s %>"/>
  <% end %>
  <% if alternate_path2.present? %>
    <link rel="alternate" href="<%= alternate_path2 %>" hreflang="<%= locale.to_s %>"/>
  <% end %>
  <% if alternate_path3.present? %>
    <link rel="alternate" href="<%= alternate_path3 %>" hreflang="<%= locale.to_s %>"/>
  <% end %>

  <% I18n.available_locales.each do |locale| %>
    <% if locale != I18n.locale %>
      <% if alternate_path3.present? %>
        <% path_only = URI.parse(alternate_path3).path %>
        <% new_path = path_only.sub(/^\/(#{locales_pattern})(\/.*)?$/, "/#{locale}\\2") %>
        <% alternate_href_locale = alternate_path3.sub(path_only, new_path) %>
      
        <link rel="alternate" href="<%= alternate_href_locale %>" hreflang="<%= locale.to_s %>" />
      <% end %>

      <% if alternate_path_other_lang.present? %>
        <% path_only = URI.parse(alternate_path_other_lang).path %>
        <% new_path = path_only.sub(/^\/(#{locales_pattern})(\/.*)?$/, "/#{locale}\\2") %>
        <% alternate_href_locale = alternate_path_other_lang.sub(path_only, new_path) %>
      
        <link rel="alternate" href="<%= alternate_href_locale %>" hreflang="<%= locale.to_s %>" />
      <% end %>
    
      <% if alternate_path2.present? %>
        <% path_only = URI.parse(alternate_path2).path %>
        <% new_path = path_only.sub(/^\/(#{locales_pattern})(\/.*)?$/, "/#{locale}\\2") %>
        <% alternate_href_locale = alternate_path2.sub(path_only, new_path) %>
      
        <link rel="alternate" href="<%= alternate_href_locale %>" hreflang="<%= locale.to_s %>" />
      <% end %>
    <% end %>
  <% end %>
  
  <!-- Default to English for unmatched locales -->
  <link rel="alternate" href="https://<%= request.host_with_port %>/" hreflang="x-default" />

  <title><%= content_for?(:title) ? t('title_with_content', content: yield(:title)) : t('default_title') %></title>  
  <!-- Load Google Fonts asynchronously to avoid render blocking -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&family=Tajawal:wght@400;500;700&display=swap" media="print" onload="this.media='all'; this.onload=null;">
  <noscript><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&family=Tajawal:wght@400;500;700&display=swap"></noscript>
  
  <!-- Favicon links for all devices and browsers -->
  <link rel="icon" type="image/x-icon" href="<%= asset_path('favicon.ico') %>">
  <link rel="icon" type="image/png" sizes="32x32" href="<%= asset_path('favicon-32x32.png') %>">
  <link rel="icon" type="image/png" sizes="16x16" href="<%= asset_path('favicon-16x16.png') %>">
  <link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path('apple-touch-icon.png') %>">
  
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <% if controller_name == 'days' %>
    <link rel="preload" href="<%= asset_path('calendar.css') %>" as="style" onload="this.onload=null;this.rel='stylesheet'">
    <noscript><%= stylesheet_link_tag 'calendar', media: 'all' %></noscript>
  <% elsif controller_name == 'blogs' %>
    <link rel="preload" href="<%= asset_path('blog.css') %>" as="style" onload="this.onload=null;this.rel='stylesheet'">
    <noscript><%= stylesheet_link_tag 'blog', media: 'all' %></noscript>
  <% end %>
  <%= javascript_include_tag 'core', defer: true %>
  <% if controller_name == 'days' %>
    <%= javascript_include_tag 'calendar_bundle', defer: true %>
  <% elsif controller_name == 'visits' || controller_name == 'visas' %>
    <%= javascript_include_tag 'visits_bundle', defer: true %>
  <% end %>
  <%= csrf_meta_tags %>

  <!-- WebApplication Structured Data for SEO -->
  <% if controller_name == 'days' && action_name == 'index' %>
    <script type="application/ld+json">
    {
      "@context": "https://schema.org",
      "@type": "WebApplication",
      "name": "<%= t('common.schengen_calculator') %>",
      "url": "https://<%= request.host %>",
      "description": "<%= t('default_description') %>",
      "applicationCategory": "UtilityApplication",
      "operatingSystem": "Any",
      "browserRequirements": "Requires JavaScript",
      "offers": {
        "@type": "Offer",
        "price": "0",
        "priceCurrency": "USD"
      },
      "featureList": [
        "Track Schengen 90/180 day rule",
        "Visual calendar interface",
        "Multiple trip planning",
        "Visa holder support",
        "8 language support (EN, DE, ES, HI, TR, ZH, PT, AR)",
        "Free account and data sync"
      ],
      "inLanguage": ["en", "de", "es", "hi", "tr", "zh", "pt", "ar"]
    }
    </script>
    <% if @json_ld_faq %>
    <script type="application/ld+json">
    <%= raw @json_ld_faq.to_json %>
    </script>
    <% end %>
  <% elsif @json_ld_data %>
    <script type="application/ld+json">
    <%= raw @json_ld_data.to_json %>
    </script>
  <% end %>
</head>
<body class="<%= direction == 'rtl' ? 'rtl' : '' %>">

<%= render 'layouts/header' %>

<main class="container-fluid">
  <div class="row">
    <div class="col-md-9">
      <div class="notice">
        <%= render 'layouts/notice' %>
      </div>
      <%= yield %>
    </div>
    <div class="col-md-3 d-none d-md-block">
      <%= render 'layouts/agoda' %>
    </div>
  </div>
</main>

<%= render 'layouts/footer' %>

<!-- Eruda mobile debugging console (131KB) -->
<!-- Commented out to improve staging performance (saves ~200ms load time) -->
<!-- To re-enable for debugging mobile issues, uncomment the lines below: -->
<%# if request.host.include?('test.schengen-calculator.com') %>
  <%#= tag.script src: "https://cdn.jsdelivr.net/npm/eruda" %>
  <%#= tag.script do %>
    <%# raw "eruda.init();" %>
  <%# end %>
<%# end %>

<!-- Lazy-load third-party scripts on user interaction or after load -->
<script>
  // Flag to ensure scripts only load once
  let scriptsLoaded = false;

  function loadThirdPartyScripts() {
    if (scriptsLoaded) return;
    scriptsLoaded = true;

    // Facebook SDK
    window.fbAsyncInit = function() {
      FB.init({
        appId: '<%= AppConfig.facebook_id %>',
        autoLogAppEvents: true,
        xfbml: true,
        version: 'v19.0'
      });
    };

    // Google AdSense
    const adsScript = document.createElement('script');
    adsScript.src = 'https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8290979932488448';
    adsScript.async = true;
    adsScript.crossOrigin = 'anonymous';
    document.body.appendChild(adsScript);
  }

  // Load scripts after page is fully loaded and user interacts
  // Or automatically after 3 seconds if no interaction
  window.addEventListener('load', function() {
    let autoLoadTimer = setTimeout(loadThirdPartyScripts, 3000);
    
    // Load on first user interaction (click, scroll, touch, keydown)
    const events = ['click', 'scroll', 'touchstart', 'keydown', 'mousemove'];
    const loadOnInteraction = function() {
      clearTimeout(autoLoadTimer);
      loadThirdPartyScripts();
      events.forEach(event => {
        window.removeEventListener(event, loadOnInteraction);
      });
    };
    
    events.forEach(event => {
      window.addEventListener(event, loadOnInteraction, { once: true, passive: true });
    });
  });
</script>

</body>
</html>