src/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root 'about#about'

    resources :visits do
      collection do
        get 'for_date' # Get visits for a specific date
        get 'max_stay_info' # Get max stay info for entry date
      end
    end
    resources :visas, except: [:index, :show]
    resources :days, only: [:index]
    resources :people do
      member do
        post :set_current
        post :make_primary
      end
    end
    
    get 'my_details' => 'users#edit'
    patch 'my_details' => 'users#update'
    delete 'my_details' => 'users#destroy', as: 'delete_account'
    get 'user' => 'users#show'
    get 'about' => 'about#about'
    get 'blog' => 'blogs#index', as: :blog_index
    get 'blog/:slug' => 'blogs#show', as: :blog
    get 'about/:nationality' => 'about#about'
    get 'disclaimer' => 'about#disclaimer'
    get 'privacy' => 'about#privacy'
    get 'datadeletion' => 'about#datadeletion'
    
    get 'fix_people_migration' => 'tasks#fix_people_migration'
    get 'unlock_migrations' => 'tasks#unlock_migrations'
    get 'unlock_and_migrate' => 'tasks#unlock_and_migrate'
    get 'migrate' => 'tasks#migrate'
    get 'create' => 'tasks#create'
    get 'seed' => 'tasks#seed'
    get 'update_countries' => 'tasks#update_countries'
    get 'guest_cleanup' => 'tasks#guest_cleanup'

    devise_for :users, skip: :omniauth_callbacks, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions'
    }

  end
  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
end

src/app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  # Blog posts registry - add new posts here (most recent first)
  BLOG_POSTS = [
    {
      slug: 'extended-schengen-stay',
      published_date: Date.new(2024, 1, 15),
      reading_time: 8,
      title_key: 'blog.extendedTravel.title',
      description_key: 'blog.extendedTravel.introduction'
    }
    # Future posts added here, newest first
  ].freeze
  
  def index
    if current_user_or_guest_user.is_guest?
      if Rails.env.development?
        # In development, prevent browser caching to match production behavior
        # (Production: CloudFront's ResponseHeadersPolicy overrides Cache-Control to no-cache)
        response.headers['Cache-Control'] = 'no-cache, no-store, must-revalidate'
      else
        # Tell CloudFront to cache for 1 month (only in production)
        expires_in 1.month, public: true
      end
    end
    
    @blog_posts = blog_posts_for_locale
    
    # Redirect to most recent post
    if @blog_posts.any?
      redirect_to blog_path(locale: I18n.locale, slug: @blog_posts.first[:slug])
    else
      render plain: 'No blog posts available', status: :not_found
    end
  end

  def show
    if current_user_or_guest_user.is_guest?
      if Rails.env.development?
        # In development, prevent browser caching to match production behavior
        # (Production: CloudFront's ResponseHeadersPolicy overrides Cache-Control to no-cache)
        response.headers['Cache-Control'] = 'no-cache, no-store, must-revalidate'
      else
        # Tell CloudFront to cache for 1 month (only in production)
        expires_in 1.month, public: true
      end
    end
    
    @blog_posts = blog_posts_for_locale
    @current_slug = params[:slug]
    
    # Set blog-specific meta tags
    set_blog_meta_tags(@current_slug)
    
    render "blogs/#{@current_slug}", layout: 'application'
  rescue ActionView::MissingTemplate
    render file: 'public/404.html', status: :not_found
  end
  
  private
  
  def blog_posts_for_locale
    BLOG_POSTS.map do |post|
      post.merge(
        title: I18n.t(post[:title_key]),
        description: I18n.t(post[:description_key]).truncate(160)
      )
    end
  end
  
  def set_blog_meta_tags(slug)
    case slug
    when 'extended-schengen-stay'
      @meta_description = I18n.t('blog.extendedTravel.introduction').truncate(160)
      @meta_title = I18n.t('blog.extendedTravel.title')
      @og_type = 'article'
      @og_url = "https://#{request.host_with_port}#{request.path}"
      # Use full URL for og:image (required for Facebook)
      image_path = view_context.asset_path('switzerland.jpg')
      @og_image = "https://#{request.host_with_port}#{image_path}"
      @og_site_name = I18n.t('common.schengen_calculator')
      @article_published_time = "2024-01-15T00:00:00Z"
      @article_modified_time = "2024-01-15T00:00:00Z"
    end
  end
end

src/app/views/blogs/_sidebar.html.haml
%nav.page-sidebar.position-sticky.d-none.d-lg-block
  %h4.title
    = t('blog.index.title')
  %ul.nav.flex-column.page-sidenav
    - @blog_posts.each do |post|
      %li{class: ('active' if post[:slug] == @current_slug)}
        = link_to blog_path(locale: I18n.locale, slug: post[:slug]), class: "text-dark" do
          .post-date
            = l(post[:published_date], format: :short)
          .post-title
            = post[:title]
          .post-meta
            %small
              %i.fa.fa-clock-o
              = t('blog.index.reading_time', minutes: post[:reading_time])

src/app/views/blogs/extended-schengen-stay.html.haml
- title t('blog.extendedTravel.title')
- content_for :meta_description, t('blog.extendedTravel.introduction').truncate(160)

.row
  .col-lg-3{role: "complementary"}
    = render 'blogs/sidebar'
  
  .col-lg-9{role: "main"}
    .blog-article
      -# Breadcrumb navigation and schema (hidden but accessible)
      .sr-only-heading
        - breadcrumbs = [{ :name => t('common.home'), :url => root_url(:locale => I18n.locale) }, { :name => t('common.blog'), :url => blog_index_url(:locale => I18n.locale) }, { :name => t('blog.extendedTravel.title'), :url => blog_url(:slug => 'extended-schengen-stay', :locale => I18n.locale) }]
        = render_breadcrumbs(breadcrumbs)
      
      %article
        %header.article-header
          %h1.article-title= t('blog.extendedTravel.title')
          .article-meta
            .meta-item
              %i.fa.fa-user
              %span= t('common.schengen_calculator')
            .meta-item
              %i.fa.fa-calendar
              %time{datetime: "2024-01-15"}= l(Date.new(2024, 1, 15), format: :long)
            .meta-item
              %i.fa.fa-clock-o
              %span= t('blog.index.reading_time', minutes: 8)
        
        .article-hero
          %picture
            %source{srcset: "#{image_path('switzerland-400w.webp')} 400w, #{image_path('switzerland-800w.webp')} 800w, #{image_path('switzerland.webp')} 1080w", type: "image/webp", sizes: "(max-width: 576px) 100vw, (max-width: 992px) 50vw, 350px"}
            = image_tag("switzerland.jpg", class: "hero-image", alt: "Swiss Alps mountain landscape - Extended European travel guide for maximizing your 90 days in Schengen Area", loading: "eager", fetchpriority: "high", width: 1080, height: 810, srcset: "#{image_path('switzerland-400w.jpg')} 400w, #{image_path('switzerland-800w.jpg')} 800w, #{image_path('switzerland.jpg')} 1080w", sizes: "(max-width: 576px) 100vw, (max-width: 992px) 50vw, 350px")
        
        .article-content
          %section.intro-section
            %p.lead= t('blog.extendedTravel.introduction')
          
          %section
            %h2= t('blog.extendedTravel.understandingTitle')
            %p= t('blog.extendedTravel.understandingContent')
            
            .info-box
              %h4
                %i.fa.fa-info-circle
                Key Point: The 90/180 Rolling Rule
              %p= t('blog.extendedTravel.understanding90Content')
          
          %section
            %h2= t('blog.extendedTravel.nearbyTitle')
            %p= t('blog.extendedTravel.nearbyContent')
            
            %ul.country-list
              - t('blog.extendedTravel.countries').each do |country|
                %li
                  %strong= country[:name] + ":"
                  = country[:description]
            
            %p= t('blog.extendedTravel.accessibilityContent')
            
            .figure
              %picture
                %source{srcset: "#{image_path('schengen-countries-map-2025-400w.webp')} 400w, #{image_path('schengen-countries-map-2025-800w.webp')} 800w, #{image_path('schengen-countries-map-2025.webp')} 1600w", type: "image/webp", sizes: "(max-width: 576px) 100vw, (max-width: 992px) 50vw, 350px"}
                = image_tag("schengen-countries-map-2025.png", class: "img-fluid", alt: "2025 Schengen Area map showing all 29 member countries including Bulgaria, Romania, and neighboring non-Schengen European countries", loading: "lazy", width: 1600, height: 1365, srcset: "#{image_path('schengen-countries-map-2025-400w.png')} 400w, #{image_path('schengen-countries-map-2025-800w.png')} 800w, #{image_path('schengen-countries-map-2025.png')} 1600w", sizes: "(max-width: 576px) 100vw, (max-width: 992px) 50vw, 350px")
              %figcaption
                = t('blog.extendedTravel.mapCaption')
                %br
                %small
                  = t('blog.extendedTravel.mapCredit_prefix', author: 'Evan Centanni')
                  = link_to t('blog.extendedTravel.mapCredit_source'), "https://www.polgeonow.com/2020/03/what-is-schengen-list-countries-map.html", target: "_blank", rel: "noopener"
                  = '. '
                  = t('blog.extendedTravel.mapLicense_label')
                  = ' '
                  = link_to t('blog.extendedTravel.mapLicense_name'), "https://creativecommons.org/licenses/by-sa/3.0/deed.en", target: "_blank", rel: "noopener"
          
          %section
            %h2= t('blog.extendedTravel.maximizingTitle')
            %p= t('blog.extendedTravel.maximizingContent')
            
            .strategy-steps
              = t('blog.extendedTravel.maximizingContentContinued').html_safe
            
            .tip-box
              %h4
                %i.fa.fa-lightbulb-o
                Pro Tip
              %p= t('blog.extendedTravel.repeatPatternContent')
          
          %section.cta-section
            .cta-box
              %h3
                %i.fa.fa-calculator
                = t('blog.extendedTravel.ctaTitle')
              %p= t('blog.extendedTravel.schengenButtonIntro')
              = link_to visits_path(locale: I18n.locale), class: "cta-button" do
                = t('blog.extendedTravel.schengenButtonTitle')
                %i.fa.fa-arrow-right
              %p.mt-3
                = t('blog.extendedTravel.schengenAboutIntro')
                = link_to t('blog.extendedTravel.schengenAboutLink'), about_path(locale: I18n.locale), class: "text-link"
          
          %section.conclusion
            %h2= t('blog.extendedTravel.conclusionTitle')
            %p= t('blog.extendedTravel.conclusionContent')
        
        %footer.article-footer
          .share-section
            %h4= t('blog.extendedTravel.shareHeading')
            .share-buttons
              %a.share-btn.x-twitter{href: "#", target: "_blank", rel: "noopener", data: {share: "twitter"}}
                %i.fa-brands.fa-x-twitter
              %a.share-btn.facebook{href: "#", target: "_blank", rel: "noopener", data: {share: "facebook"}}
                %i.fa-brands.fa-facebook
              %a.share-btn.linkedin{href: "#", target: "_blank", rel: "noopener", data: {share: "linkedin"}}
                %i.fa-brands.fa-linkedin

:javascript
  // Structured data for SEO
  const structuredData = {
    "@context": "https://schema.org",
    "@type": "BlogPosting",
    "headline": "#{t('blog.extendedTravel.title')}",
    "image": "#{image_url('switzerland.jpg')}",
    "author": {
      "@type": "Organization",
      "name": "Schengen Calculator"
    },
    "publisher": {
      "@type": "Organization",
      "name": "Schengen Calculator",
      "logo": {
        "@type": "ImageObject",
        "url": "#{image_url('med.png')}"
      }
    },
    "datePublished": "2024-01-15",
    "dateModified": "2024-01-15",
    "description": "#{t('blog.extendedTravel.introduction').truncate(160)}"
  };
  
  const script = document.createElement('script');
  script.type = 'application/ld+json';
  script.text = JSON.stringify(structuredData);
  document.head.appendChild(script);

  // Social media sharing functionality
  document.addEventListener('DOMContentLoaded', function() {
    const pageUrl = encodeURIComponent(window.location.href);
    const pageTitle = encodeURIComponent(document.title);
    
    // Share button click handlers
    document.querySelectorAll('.share-btn').forEach(function(btn) {
      btn.addEventListener('click', function(e) {
        e.preventDefault();
        const platform = this.getAttribute('data-share');
        let shareUrl = '';
        
        switch(platform) {
          case 'twitter':
            shareUrl = 'https://twitter.com/intent/tweet?url=' + pageUrl + '&text=' + pageTitle;
            break;
          case 'facebook':
            shareUrl = 'https://www.facebook.com/sharer/sharer.php?u=' + pageUrl;
            break;
          case 'linkedin':
            shareUrl = 'https://www.linkedin.com/sharing/share-offsite/?url=' + pageUrl;
            break;
        }
        
        if (shareUrl) {
          window.open(shareUrl, 'share-dialog', 'width=600,height=600');
        }
      });
    });
  });

src/app/views/blogs/index.html.haml
= link_to t('blog.extendedTravel.title'), blog_path(locale: I18n.locale, slug: 'extended-schengen-stay')