src/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root 'about#about'

    resources :visits do
      collection do
        get 'for_date' # Get visits for a specific date
        get 'max_stay_info' # Get max stay info for entry date
      end
    end
    resources :visas, except: [:index, :show]
    resources :days, only: [:index]
    resources :people do
      member do
        post :set_current
        post :make_primary
      end
    end
    
    get 'my_details' => 'users#edit'
    patch 'my_details' => 'users#update'
    delete 'my_details' => 'users#destroy', as: 'delete_account'
    get 'user' => 'users#show'
    get 'about' => 'about#about'
    get 'blog' => 'blogs#index', as: :blog_index
    get 'blog/:slug' => 'blogs#show', as: :blog
    get 'about/:nationality' => 'about#about'
    get 'disclaimer' => 'about#disclaimer'
    get 'privacy' => 'about#privacy'
    get 'datadeletion' => 'about#datadeletion'
    
    get 'fix_people_migration' => 'tasks#fix_people_migration'
    get 'unlock_migrations' => 'tasks#unlock_migrations'
    get 'unlock_and_migrate' => 'tasks#unlock_and_migrate'
    get 'migrate' => 'tasks#migrate'
    get 'create' => 'tasks#create'
    get 'seed' => 'tasks#seed'
    get 'update_countries' => 'tasks#update_countries'
    get 'guest_cleanup' => 'tasks#guest_cleanup'

    devise_for :users, skip: :omniauth_callbacks, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions'
    }

  end
  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
end

src/app/models/person.rb
class Person < ApplicationRecord
  belongs_to :user
  belongs_to :nationality, class_name: 'Country', foreign_key: :nationality_id, optional: true
  has_many :visits, dependent: :delete_all
  has_many :visas, dependent: :delete_all

  validates :first_name, presence: true
  validates :user_id, presence: true

  scope :ordered, -> { order(is_primary: :desc).order(Arel.sql("LOWER(COALESCE(first_name, '') || ' ' || COALESCE(last_name, ''))")) }

  before_destroy :prevent_primary_person_deletion
  before_destroy :prevent_last_person_deletion
  before_save :ensure_single_primary_for_user, if: :becoming_primary?

  def full_name
    [first_name, last_name].compact.join(' ')
  end

  def nationality_with_default
    nationality || Country.find_by(country_code: "US")
  end

  def visa_required?
    nationality_with_default.visa_required == 'V'
  end

  private

  def becoming_primary?
    will_save_change_to_is_primary? && is_primary? && user.present?
  end

  def ensure_single_primary_for_user
    user.people.where.not(id: id).where(is_primary: true).update_all(is_primary: false)
  end

  def prevent_primary_person_deletion
    if is_primary
      errors.add(:base, "Cannot delete the primary person. Please make another person primary first.")
      throw(:abort)
    end
  end

  def prevent_last_person_deletion
    if user.people.count == 1
      errors.add(:base, "Cannot delete your only person")
      throw(:abort)
    end
  end
end

src/app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:edit, :update, :destroy, :set_current, :make_primary]

  def index
    @people = current_user_or_guest_user.people.ordered
  end

  def new
    @person = current_user_or_guest_user.people.new
    # Pre-fill nationality from primary person
    primary_person = current_user_or_guest_user.people.find_by(is_primary: true)
    @person.nationality_id = primary_person&.nationality_id
  end

  def create
    @person = current_user_or_guest_user.people.new(person_params)
    
    if @person.save
      # Track analytics when users create additional people (not primary)
      if current_user_or_guest_user.people.count > 1
        tracker = Staccato.tracker('UA-67599800-1', current_user_or_guest_user.id)
        tracker.event(category: 'people', action: 'create_additional_person', label: 'multi_person_tracking', value: 1)
      end
      
      redirect_to people_path, notice: 'Person was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @person.update(person_params)
      redirect_to people_path, notice: 'Person was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @person.is_primary
      redirect_to people_path, alert: 'Cannot delete the primary person. Please make another person primary first.'
    elsif @person.destroy
      redirect_to people_path, notice: 'Person was successfully deleted.'
    else
      redirect_to people_path, alert: @person.errors.full_messages.join(', ')
    end
  end

  def set_current
    session[:current_person_id] = @person.id
    safe_name = ERB::Util.html_escape(@person.full_name)
    redirect_back_or_to root_path, notice: "Switched to #{safe_name}"
  end

  def make_primary
    # Remove primary status from all user's people
    current_user_or_guest_user.people.update_all(is_primary: false)
    
    # Make this person primary
    @person.update(is_primary: true)

    safe_name = ERB::Util.html_escape(@person.full_name)
    redirect_back_or_to people_path, notice: "#{safe_name} is now your primary person"
  end

  private

  def set_person
    @person = current_user_or_guest_user.people.find(params[:id])
  end

  def person_params
    params.require(:person).permit(:first_name, :last_name, :nationality_id)
  end
end

src/app/helpers/people_helper.rb
module PeopleHelper
end

src/app/views/people/_form.html.haml
= form_for @person, :html => {:class => "form-horizontal"} do |f|
  - if @person.errors.any?
    #error_explanation.alert.alert-danger
      %h4= t('people.form.errors.heading', count: @person.errors.count)
      %ul
        - @person.errors.full_messages.each do |msg|
          %li= msg
  .form-group.row
    .col-sm-2.my-auto
      = f.label :first_name, class: "col-form-label"
    .col-sm-10
      = f.text_field :first_name, :class => "form-control", required: true
      %small.form-text.text-muted= t('people.form.required_hint')
  .form-group.row
    .col-sm-2.my-auto
      = f.label :last_name, class: "col-form-label"
    .col-sm-10
      = f.text_field :last_name, :class => "form-control"
      %small.form-text.text-muted= t('people.form.optional_hint')
  .form-group.row
    .col-sm-2.my-auto
      = f.label :nationality_id, class: "col-form-label"
    .col-sm-10
      = f.collection_select(:nationality_id, Country.all.order_by_name, :id, :name, {include_blank: t('people.form.nationality_placeholder')}, {:class => "form-control custom-select"})
  .actions
    .form-group.row
      .col-sm-12
        = f.submit t('common.save'), class: "btn btn-primary form-btn float-right"

src/app/views/people/edit.html.haml
.container-fluid.mt-4
  .d-flex.justify-content-between.align-items-center.mb-3
    %h1.mb-0 Edit Person
    = link_to people_path(locale: I18n.locale), class: 'btn btn-outline-primary' do
      %i.fa.fa-users.mr-2
      Manage People

  = render 'form'

  .mt-3
    = link_to 'Back', people_path, class: 'btn btn-secondary'

src/app/views/people/index.html.haml
.row.mt-4
  .col-lg-9
    %h1.h3.mb-3
      %i.fa.fa-users.mr-2
      = t('common.manage_people')

    - if @people.count == 1
      .alert.alert-info
        %i.fa.fa-info-circle.mr-2
        = t('people.index.single_person_notice')

    .row.py-1.mb-3
      .col-auto
        = link_to my_details_path(locale: I18n.locale), class: "btn btn-outline-primary btn-md" do
          %i.fa.fa-user-cog.mr-2
          = t('common.manage_account')
      .col-auto.ml-auto
        = link_to new_person_path(locale: I18n.locale), class: "btn btn-add btn-md" do
          %i.fa.fa-plus.mr-2
          = t('common.add_person')

    - if @people.empty?
      .empty-state
        .empty-icon
          %i.fa.fa-users
        %h4= t('people.index.empty_state.title')
        %p= t('people.index.empty_state.description')
        = link_to new_person_path(locale: I18n.locale), class: "btn btn-add btn-lg" do
          %i.fa.fa-plus.mr-2
          = t('common.add_person')
    - else
      .responsive-table-container
        %table.table.table-striped.table-bordered.table-hover.responsive-table
          %caption= t('people.index.table.caption')
          %thead.bg-header
            %tr
              %th{scope: "col"}= t('people.index.table.columns.name')
              %th{scope: "col"}= t('people.index.table.columns.nationality')
              %th{scope: "col"}= t('people.index.table.columns.status')
              %th{scope: "col", class: 'modify-col'}= t('people.index.table.columns.actions')
          %tbody
            - @people.each do |person|
              %tr{class: (person == current_person ? 'table-active' : ''), data: {person_url: (set_current_person_path(person) unless person == current_person)}, style: (person == current_person ? '' : 'cursor: pointer;')}
                %th{scope: "row", class: 'bg-md-header'}
                  = person.full_name
                %td{"data-title": t('people.index.table.columns.nationality')}
                  = person.nationality&.localized_name || t('common.person_not_set')
                %td{"data-title": t('people.index.table.columns.status'), onclick: "event.stopPropagation();"}
                  - if person == current_person
                    %span.badge.badge-success.mr-2= t('people.index.table.badges.active')
                  - if person.is_primary
                    %span.badge.badge-info= t('people.index.table.badges.primary')
                  - else
                    = button_to make_primary_person_path(person, locale: I18n.locale), method: :post, class: "btn btn-sm btn-outline-primary", title: t('people.index.table.make_primary.title'), "aria-label": t('people.index.table.make_primary.aria', name: person.full_name), form: { class: "d-inline" } do
                      = t('people.index.table.make_primary.label')
                %td{"data-title": t('people.index.table.columns.actions'), onclick: "event.stopPropagation();"}
                  .action-buttons
                    = link_to edit_person_path(person, locale: I18n.locale), class: "btn btn-sm btn-icon", title: t('common.edit'), "aria-label": t('people.index.table.actions.edit_aria', name: person.full_name) do
                      %i.fa.fa-pencil-alt{"aria-hidden": "true"}
                    - unless person.is_primary
                      %a.btn.btn-sm.btn-icon.delete-person-link{href: "#", data: {delete_url: person_path(person, locale: I18n.locale), delete_message: t('people.index.delete_person_warning', person: person.full_name)}, title: t('common.delete'), "aria-label": t('people.index.table.actions.delete_aria', name: person.full_name)}
                        %i.fa.fa-trash{"aria-hidden": "true"}

    .row
      .col-lg-10.col-md-12
        .ad-block-limit.d-none.d-md-block
          %ins.adsbygoogle{"data-ad-client" => "ca-pub-8290979932488448", "data-ad-format" => "auto", "data-ad-slot" => "3629950616", :style => "display:block"}
  .col-lg-3.d-none.d-lg-block.mb-5{style: "padding-bottom: 220px;"}
    = render 'days/calendar_sidebar', show_legend: false

.row.d-lg-none.mt-2
  .col-12
    = render 'days/calendar_sidebar', sticky_sidebar: false, show_legend: false

-# Modal for delete confirmation
#deleteModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "deleteModalLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog{role: "document"}
    .modal-content
      .modal-header.delete-warning
        %h5#deleteModalLabel.modal-title
          %i.fa.fa-exclamation-triangle.mr-2{"aria-hidden" => "true"}
          = t('common.confirm_delete')
        %button.close.text-white{"aria-label" => "Close", "data-dismiss" => "modal", type: "button"}
          %span{"aria-hidden" => "true"} &times;
      .modal-body
        %p#deleteModalMessage= t('common.delete_warning')
      .modal-footer
        %button.btn.btn-secondary{"data-dismiss" => "modal", type: "button"}= t('common.cancel')
        %a#deleteConfirmButton.btn.btn-danger{href: "#"}
          %i.fa.fa-trash.mr-2{"aria-hidden" => "true"}
          = t('common.delete')

:javascript
  (adsbygoogle = window.adsbygoogle || []).push({});

:javascript
  document.addEventListener('DOMContentLoaded', function() {
    // Handle row clicks to switch person
    const rows = document.querySelectorAll('table tbody tr[data-person-url]');
    
    rows.forEach(function(row) {
      row.addEventListener('click', function(e) {
        const url = row.dataset.personUrl;
        if (url) {
          // Create and submit a form for POST request
          const form = document.createElement('form');
          form.method = 'POST';
          form.action = url;
          
          const csrfToken = document.querySelector('meta[name="csrf-token"]').content;
          const csrfInput = document.createElement('input');
          csrfInput.type = 'hidden';
          csrfInput.name = 'authenticity_token';
          csrfInput.value = csrfToken;
          form.appendChild(csrfInput);
          
          document.body.appendChild(form);
          form.submit();
        }
      });
    });
    
    // Handle delete button clicks
    const deleteButtons = document.querySelectorAll('.delete-person-link');
    const $modal = $('#deleteModal');
    const $confirmButton = $('#deleteConfirmButton');
    
    deleteButtons.forEach(function(button) {
      button.addEventListener('click', function(e) {
        e.preventDefault();
        e.stopPropagation();
        
        const deleteUrl = button.dataset.deleteUrl;
        const deleteMessage = button.dataset.deleteMessage;
        
        // Update modal message with localized text
        $('#deleteModalMessage').text(deleteMessage);
        
        // Show the modal
        $modal.modal('show');
        
        // Handle delete confirmation click
        $confirmButton.off('click').on('click', function(e) {
          e.preventDefault();
          
          // Create a form to submit the DELETE request
          const form = document.createElement('form');
          form.method = 'POST';
          form.action = deleteUrl;
          
          const csrfToken = document.querySelector('meta[name="csrf-token"]').content;
          const csrfInput = document.createElement('input');
          csrfInput.type = 'hidden';
          csrfInput.name = 'authenticity_token';
          csrfInput.value = csrfToken;
          form.appendChild(csrfInput);
          
          const methodInput = document.createElement('input');
          methodInput.type = 'hidden';
          methodInput.name = '_method';
          methodInput.value = 'delete';
          form.appendChild(methodInput);
          
          document.body.appendChild(form);
          form.submit();
        });
      });
    });
  });

src/app/views/people/new.html.haml
.container-fluid.mt-4
  %h1= t('people.new.title')

  = render 'form'

  .mt-3
    = link_to t('common.back'), people_path, class: 'btn btn-secondary'